In [56]:
import pandas as pd
df=pd.read_csv("apple_quality.csv")
df

,A_id,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
0,0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1,1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2,2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3,3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4,4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...,...
3996,3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997,3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998,3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999,3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [57]:
X1=df.drop(columns=['A_id','Acidity'])
X1

          Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness Quality
0    -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840    good
1    -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530    good
2    -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033     bad
3    -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761    good
4     1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849    good
...        ...       ...        ...          ...        ...       ...     ...
3996 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900    good
3997 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859     bad
3998 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488    good
3999  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571    good
4000       NaN       NaN        NaN          NaN        NaN       NaN     NaN

[4001 rows x 7 columns]

In [58]:
X1.isna().sum()

Size           1
Weight         1
Sweetness      1
Crunchiness    1
Juiciness      1
Ripeness       1
Quality        1
dtype: int64

In [59]:
X1=X1.dropna()
X1

          Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness Quality
0    -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840    good
1    -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530    good
2    -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033     bad
3    -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761    good
4     1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849    good
...        ...       ...        ...          ...        ...       ...     ...
3995  0.059386 -1.067408  -3.714549     0.473052   1.697986  2.244055     bad
3996 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900    good
3997 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859     bad
3998 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488    good
3999  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571    good

[4000 rows x 7 columns]

In [60]:
X1.isna().sum()

Size           0
Weight         0
Sweetness      0
Crunchiness    0
Juiciness      0
Ripeness       0
Quality        0
dtype: int64

In [61]:
gb={'good':1,'bad':0}
# X['Quality']=X['Quality'].map(gb)
X1['Quality']=X1['Quality'].replace(['good','bad'],[1,0])
X1

C:\conda_tmp\ipykernel_12972\1365532653.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X1['Quality']=X1['Quality'].replace(['good','bad'],[1,0])

          Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  Quality
0    -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840        1
1    -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530        1
2    -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033        0
3    -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761        1
4     1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849        1
...        ...       ...        ...          ...        ...       ...      ...
3995  0.059386 -1.067408  -3.714549     0.473052   1.697986  2.244055        0
3996 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900        1
3997 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859        0
3998 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488        1
3999  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571        1

[4000 rows x 7 columns]

In [62]:
X=X1.drop(columns=['Quality'])
X

          Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness
0    -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840
1    -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530
2    -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033
3    -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761
4     1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849
...        ...       ...        ...          ...        ...       ...
3995  0.059386 -1.067408  -3.714549     0.473052   1.697986  2.244055
3996 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900
3997 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859
3998 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488
3999  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571

[4000 rows x 6 columns]

In [63]:
Y=X1[['Quality']]
Y

      Quality
0           1
1           1
2           0
3           1
4           1
...       ...
3995        0
3996        1
3997        0
3998        1
3999        1

[4000 rows x 1 columns]

In [64]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(3200, 6) (800, 6) (3200, 1) (800, 1)

In [65]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,LogisticRegression

In [66]:
m1=LinearRegression()
m1.fit(X_train,Y_train)
print(f"Linear Regression Train Score : {m1.score(X_train,Y_train)}")
print(f"Linear Regression Test Score : {m1.score(X_test,Y_test)}")

Linear Regression Train Score : 0.2511735447872593
Linear Regression Test Score : 0.29027028287866163

In [67]:
m2=Lasso(alpha=25,max_iter=100,tol=0.1)
m2.fit(X_train,Y_train)
print(f"Lasso Train Score : {m2.score(X_train,Y_train)}")
print(f"Lasso Test Score : {m2.score(X_test,Y_test)}")

Lasso Train Score : 0.0
Lasso Test Score : -7.656441411052484e-05

In [68]:
m3=Ridge(alpha=25,max_iter=100,tol=0.1)
m3.fit(X_train,Y_train)
print(f"Ridge Train Score : {m3.score(X_train,Y_train)}")
print(f"Ridge Regression Test Score : {m3.score(X_test,Y_test)}")

Ridge Train Score : 0.2511705609544511
Ridge Regression Test Score : 0.29016304783466673

In [69]:
m5=LogisticRegression()
m5.fit(X_train,Y_train)
print(f"Logistic Regression Train Score : {m5.score(X_train,Y_train)}")
print(f"Logistic Regression Test Score : {m5.score(X_test,Y_test)}")

Logistic Regression Train Score : 0.731875
Logistic Regression Test Score : 0.7375

D:\installed_files\Python\Lib\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [70]:
from sklearn.tree import DecisionTreeClassifier
m4=DecisionTreeClassifier()
m4.fit(X_train,Y_train)
print(f"Decision tree Classifier Train Score : {m4.score(X_train,Y_train)}")
print(f"Decision tree Classifier Test Score : {m4.score(X_test,Y_test)}")

Decision tree Classifier Train Score : 1.0
Decision tree Classifier Test Score : 0.80375